#!/usr/bin/env python3
import sys
import json

sys.path.append('/opt/ucloud/extensions/lib')
from common import *

# =====================================================================================================================
# Loading request
# =====================================================================================================================

with open(sys.argv[1]) as fp:
    request = json.load(fp)

owner = request['owner']
owner_type = owner['type']

# =====================================================================================================================
# Mapping
# =====================================================================================================================

if owner_type == 'user':
    response = { 'account' : get_username_by_uid(owner['uid']) }
    print(json.dumps(response))

elif owner_type == 'project':
    response = { 'account' : get_group_by_gid(owner['gid']) }
    print(json.dumps(response))

else:
    print(f'Unknown owner type {owner_type}')
    exit(1)
