#!/usr/bin/env python3
import sys
import json

sys.path.append('/opt/ucloud/extensions/lib')
from common import *

# =====================================================================================================================
# Loading request
# =====================================================================================================================

with open(sys.argv[1]) as fp:
    request = json.load(fp)

owner_type = request['type']

# =====================================================================================================================
# Mapping
# =====================================================================================================================

if owner_type == 'user':
    username = get_username_by_uid(request['uid'])
    response = {
        'title' : 'Home',
        'path' : f'/home/{username}'
    }
    print(json.dumps([response]))

elif owner_type == 'project':
    group_name = get_group_by_gid(request['gid'])
    response = {
        'title' : 'Work',
        'path' : f'/work/{group_name}'
    }
    print(json.dumps([response]))

else:
    print(f'Unknown owner type {owner_type}')
    exit(1)
