#!/usr/bin/env python3
import re
import sys
import subprocess
import urllib3
import json

sys.path.append('/opt/ucloud/extensions/lib')
urllib3.disable_warnings()

from ipa import *
from ess import *
from slurm import *
from common import *

# =====================================================================================================================
# Loading request
# =====================================================================================================================

request = json.loads(open(sys.argv[1]).read())
balance = request['balance']
owner = request['owner']
owner_type = owner['type']

# =====================================================================================================================
# Allocating resources
# =====================================================================================================================

slurm_account = None

if owner_type == 'user':
    slurm_account = get_username_by_uid(owner['uid'])
elif owner_type == 'project':
    slurm_account = get_group_by_gid(owner['gid'])
else:
    print(f'Unknown owner_type {owner_type}')
    exit(1)

if slurm_account is None:
    print('Could not resolve slurm account')
    exit(1)

args = {
    'account' : slurm_account,
    'credits' : balance
}

try:
    slurm_account_modify(args)
except:
    print(f'Failed to modify account with {args}')

print('{ "type": "ucloud_managed" }')
