#!/usr/bin/env python3
import sys
import urllib3
import json

sys.path.append('/opt/ucloud/extensions/lib')
urllib3.disable_warnings()

from ipa import *
from ess import *
from slurm import *
from common import *

# ==============================================================================
# Loading request
# ==============================================================================

with open(sys.argv[1]) as fp:
    request = json.load(fp)

balance = request['balance']
owner = request['owner']
owner_type = owner['type']

# ==============================================================================
# Allocating resources
# ==============================================================================

slurm_account = None

if owner_type == 'user':
    slurm_account = get_username_by_uid(owner['uid'])
elif owner_type == 'project':
    slurm_account = get_group_by_gid(owner['gid'])
else:
    sys.exit(f'Unknown owner type: {owner_type}')

if slurm_account is None:
    sys.exit('Could not resolve slurm account')

args = {
    'account' : slurm_account,
    'credits' : balance
}

slurm_account_modify(args)
print('{ "type": "ucloud_managed" }')
