#!/usr/bin/env python3
import sys
import urllib3
import json

sys.path.append('/opt/ucloud/extensions/lib')
urllib3.disable_warnings()

from ipa import *
from ess import *
from slurm import *
from common import *

# =====================================================================================================================
# Authenticate with services
# =====================================================================================================================

with open('/etc/ucloud/ess.json') as fp:
    config = json.load(fp)

auth_ok = ess_authenticate(config['username'], config['password'], config['server'])
if not auth_ok:
    print('Could not authenticate with ESS')
    exit(1)

# =====================================================================================================================
# Loading request
# =====================================================================================================================

with open(sys.argv[1]) as fp:
    request = json.load(fp)

balance = request['balance']
owner = request['owner']
owner_type = owner['type']

# =====================================================================================================================
# Allocating resources
# =====================================================================================================================

args = {
    'filesystem' : 'ess1',
    'space' : f'{balance}G',
    'files' : '0'
}

if owner_type == 'user':
    username = get_username_by_uid(owner['uid'])
    args['fileset'] = f'home-{username}'

elif owner_type == 'project':
    group_name = get_group_by_gid(owner['gid'])
    args['fileset'] = f'work-{group_name}'

else:
    print(f'Unknown owner_type {owner_type}')
    exit(1)

ess_fileset_quota(args)

print('{ "type": "ucloud_managed" }')
