#!/usr/bin/env python3
import re
import sys
import urllib3
import json

sys.path.append('/opt/ucloud/extensions/lib')
urllib3.disable_warnings()

from ipa import *
from ess import *
from slurm import *
from common import *

# =====================================================================================================================
# Configuration
# =====================================================================================================================

FREE_CORE_HOURS = 10
FREE_QUOTA_GIGS = 10

ESS_FILE_SYSTEM = 'ess1'
ESS_PATH_PREFIX = '/gpfs/ess1/work/'

# =====================================================================================================================
# Loading request
# =====================================================================================================================

request = json.loads(open(sys.argv[1]).read())
request_type = request['type']

# =====================================================================================================================
# Utilities
# =====================================================================================================================

def generate_name(ucloud_title, allocated_gid):
    return re.sub(r'[^a-z0-9]', '_', ucloud_title.lower()) + '_' + str(allocated_gid)

def create_group(gid, name):
    try:
        args = { 'group' : name, 'gid' : gid }
        ipa_group_create(args)
    except NameError:
        pass

    try:
        args = { 'parent' : 'hippo_users', 'group' : name }
        ipa_group_add_group(args)
    except NameError:
        pass

    run_command(['sudo', '/sbin/sss_cache', '-E'])

def delete_group(gid):
    group_name = get_group_by_gid(gid)
    if group_name is not None:
        ipa_group_delete({ 'group' : group_name })

def add_user_to_group(uid, gid):
    group_name = get_group_by_gid(gid)
    username = get_username_by_uid(uid)
    if group_name is not None and username is not None:
        ipa_group_add_user({ 'user' : username, 'group' : group_name })
    run_command(['sudo', '/sbin/sss_cache', '-E'])

def remove_user_from_group(uid, gid):
    group_name = get_group_by_gid(gid)
    username = get_username_by_uid(uid)
    if group_name is not None and username is not None:
        ipa_group_remove_user({ 'user' : username, 'group' : group_name })

# =====================================================================================================================
# Authenticate with services
# =====================================================================================================================

ess_config = json.loads(open('/etc/ucloud/ess.json').read())
ess_auth_ok = ess_authenticate(ess_config['username'], ess_config['password'], ess_config['server'])
if not ess_auth_ok:
    print('Could not authenticate with ESS')
    exit(1)

ipa_config = json.loads(open('/etc/ucloud/ipa.json').read())
ipa_auth_ok = ipa_authenticate(ipa_config['username'], ipa_config['password'], ipa_config['server'], ipa_config['cert'])
if not ipa_auth_ok:
    print('Could not authenticate with IPA')
    exit(1)

# =====================================================================================================================
# Event handler
# =====================================================================================================================

if request_type == 'project_renamed':
    gid = request['newProject']['localId']
    if request['oldProject'] is None:
        ucloud_project_id = request['newProject']['project']['id']
        name = generate_name(request['newTitle'], gid)
        create_group(gid, name)

        args = {
            'account' : name,
            'credits' : FREE_CORE_HOURS * 60,
            'description' : f'UCloud Project {ucloud_project_id}',
            'organization' : 'ucloud'
        }
        try:
            slurm_account_create(args)
        except NameError as e:
            if 'slurm account already exists' in str(e):
                pass
            else:
                raise e

        args = {
            'filesystem' : ESS_FILE_SYSTEM,
            'fileset' : f'work-{name}',
            'parent' : 'root',
            'path' : f'{ESS_PATH_PREFIX}{name}',
            'owner' : f'root:{name}',
            'permissions' : '2770'
        }
        ess_fileset_create(args)

        args = {
            'filesystem' : ESS_FILE_SYSTEM,
            'fileset' : f'work-{name}',
            'space' : f'{FREE_QUOTA_GIGS}G',
            'files' : '0'
        }
        ess_fileset_quota(args)

elif request_type == 'members_added_to_project':
    gid = request['newProject']['localId']
    for member in request['newMembers']:
        uid = member['uid']
        if uid is None: continue
        add_user_to_group(uid, gid)
        account_name = generate_name(request['newProject']['project']['specification']['title'], gid)
        slurm_account_add_user({ 'account' : account_name, 'user' : get_username_by_uid(uid) })

elif request_type == 'members_removed_from_project':
    gid = request['newProject']['localId']
    for member in request['removedMembers']:
        uid = member['uid']
        if uid is None: continue
        remove_user_from_group(uid, gid)
        account_name = generate_name(request['newProject']['project']['specification']['title'], gid)
        slurm_account_remove_user({ 'account' : account_name, 'user' : get_username_by_uid(uid) })

print('{}')
