#!/usr/bin/env python3
import os
import sys
import json

sys.path.append('/opt/ucloud/extensions/lib')
from common import *

# =====================================================================================================================
# Loading request
# =====================================================================================================================

request = json.loads(open(sys.argv[1]).read())
path = request['path']

# =====================================================================================================================
# Storage accounting
# =====================================================================================================================

if not os.path.isdir(path):
    print(f'Not a directory: {path}')
    exit(1)

path = path.strip('/').replace('/','-')
info = run_command(['/usr/lpp/mmfs/bin/mmlsquota', '-j', path, '-Y', 'ess1'])
info = info.stdout.split('\n')
info = info[1].split(':')
usage = int(info[10])
print(f'{{"bytesUsed":{usage}}}')
