#!/usr/bin/env python3
import os
import sys
import json

sys.path.append('/opt/ucloud/extensions/lib')
from common import *

# ==============================================================================
# Loading request
# ==============================================================================

with open(sys.argv[1]) as fp:
    request = json.load(fp)

path = request['path']

# ==============================================================================
# Storage accounting
# ==============================================================================

if not os.path.isdir(path):
    sys.exit(f'Not a directory: {path}')

path = path.strip('/').replace('/','-')
info = run_command(['/usr/lpp/mmfs/bin/mmlsquota', '-j', path, '-Y', 'ess1'])
info = info.stdout.split('\n')
info = info[1].split(':')
usage = 1024*int(info[10])

response = {
    'bytesUsed' : usage
}

print(json.dumps(response))
